<?php

    include_once '../../../B7WEB/menu.html';
    include_once '../../../B7WEB/home.html';

    include_once "tiposVariaveis.php";

    //CLASSE "main.php" É UMA CLASSE DE EXECUÇÃO E TODA A SUA FUNCIONALIDADE ESTÁ NA PRÓXIMA CLASSE "tiposVariaveis.php":

    //TUDO O QUE TIVER DIGITADO APÓS AS BARRAS "//" É UM COMENTÁRIO!
    //NENHUM COMENTÁRIO É EXECUTADO DEPOIS DE BARRAS, VEJA O EXEMPLO:
    //echo $nome = 'Werike';
    //A LINHA ACIMA É UM COMANDO QUE MOSTRA NA TELA O NOME QUE EU DEFINI PARA A VARIÁVEL.

    //A VARIÁVEL PODE RECEBER QUALQUER DADO(INFORMAÇÃO) E COMEÇANDO COM QUALQUER LETRA.
    //VEJA OS TIPOS DE VARIAVEIS QUE PODEM SER CRIADOS:

    //1- DEVEM COMEÇAR COM LETRAS
    $variavel;

    //2- PODE SER QUALQUER NOME
    $qualquer;

    //3- DEVEM RESPEITAR O MODELO CAMELCASE, VEJA O EXEMPLO DE UMA VARIÁVEL COM DUAS PALAVRAS
    $qualquerPalavra; //A PRIMEIRA LETRA DA PALAVRA "Palavra" DEVE SER MAIÚSCULA.
    //ESSE MODELO DE SER APLICADO SEMPRE PARA QUALQUER JUNÇÃO DE PALAVRAS PARA DEFINIR UMA VARIÁVEL.

    //4- NÃO PODE SER UM NOME DE VARIÁVEL JÁ EXISTENTE OU DA PRÓPRIA LINGUAGUEM DE PROGRAMAÇÃO UTILIZADA.
    
    //5- NÃO PODE COMEÇAR COM NUMEROS
    // $1numero; // DA ERRO AO CRIAR ESTA VARIÁVEL COMEÇANDO COM NÚMERO

    //CRIANDO UMA MENSAGEM PARA MOSTRAR NA TELA
    echo '<h3>Acompanhe e estude as anotações dos códigos do módulo 01 -  aula 07!</h3>';

    //GUARDANDO UM DADO NA VARIÁVEL
    //O SINAL DE "=" EM PROGRAMAÇÃO SIGNIFICA QUE ESTÁ RECEBENDO UM VALOR:
    $nome = "Werike"; // AQUI DIZ QUE A VARIÁVEL $nome RECEBE A PALAVRA/NOME "werike"
    //PARA IMPRIMIR O VALOR UTILIZE O COMANDO "echo" 
    //E DEPOIS COLOCQUE A VARIÁVEL QUE DESEJA IMPRIMIR O SEU RESULTADO 
    echo "ASPAS DUPLAS - ";
    echo "Nome: $nome<br><br>";

    //ASPAS SIMPLES IMPRIME TUDO O QUE ESTÁ DENTRO, VEJO O EXEMPLO:
    echo "ASPAS SIMPLES - ";
    echo 'Nome: $nome<br><br>'; //IMPRIME A VARIÁVEL COMO SE FOSSE UMA PALAVRA, SEM MOSTRAR O VALOR QUE FOI ATRIBUÍDO A ELA!
    
    //TIPO DE DADO INTEIRO:
    $idade = 25; //DADO DO TIPO INTEIRO
    $dormindo = false; //DADO DO TIPO BOOLEAN - É UM TIPO DE VARIÁVEL QUE RECEBE true/false SOMENTE ISSO!
    $semDados = null; //VARIÁVEL SEM NENHUM VALOR(VAZIA)

    //CHAMANDO OS MÉTODOS DAS OUTRAS CLASSES
    explicar();

    //NESTE CASO, O RETORNO DO VALOR DO MÉTODO SERÁ ATRIBUÍDO A UMA VARIÁVEL LOCAL.
    $x = valorCampo();

    //SABENDO O VALOR DA VARIÁVEL LOCAL, O MESMO SERÁ ENVIADO PARA OUTROS MÉTODOS 
    //ONDE RECEBERÁ UM TRATAMENTO DIFERENCIADO EM CADA MÉTODO.
    somar($x);
    subtrair($x);
    multiplicar($x);
    divisao($x);
    
    include_once '../../../B7WEB/footer.html';
    
?>